version: '3'
services:
  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"